### ISSUE TITLE
Add Properties to Test Map

### ISSUE THREAD

**Issue by chrisLee413** [cpe305/fall2016-project-chrisLee413#2]
Use the application 'Tiled' to add the property 'blocked' to certain tiles in the LinksHouse.tmx file.

Only focus on the walls/house/trees for now since I am just testing my collision detection.  To actually add the property you will first need to scroll through the tileset (located on the bottom right) until you find the area the map was created from.  Then you will need to click on the specific tile (in the tileset) you wish to add the property to and click on the small blue '+' sign (slightly above bottom left corner).  Call the property 'blocked', leave it as a String and click OK.

Download Tiled: https://thorbjorn.itch.io/tiled

LinksHouse.tmx file is located in desktop/assets/maps/LinksHouse.tmx

**Comment by dsabsay** [comment]
Added the "blocked" property to the walls, cliffs, and fence around the house.
